"use client";
/* eslint-disable @next/next/no-img-element */

import { useMemo, useState, type FormEvent } from "react";
import { AdminApiError } from "../api";
import type { BlogPost, PostDraft, PublishStatus } from "../types";
import type { ManagerContext } from "./AdminApp";
import Icon from "./Icon";

const emptyPost: PostDraft = { slug: "", status: "draft", titleAm: "", titleEn: "", excerptAm: "", excerptEn: "", contentAm: "", contentEn: "", coverImageUrl: "", authorName: "Aspio", tags: "", seoTitleAm: "", seoTitleEn: "", seoDescriptionAm: "", seoDescriptionEn: "" };
const toDraft = (post: BlogPost): PostDraft => ({ id: post.id, slug: post.slug, status: post.status, titleAm: post.titleAm, titleEn: post.titleEn, excerptAm: post.excerptAm, excerptEn: post.excerptEn, contentAm: post.contentAm, contentEn: post.contentEn, coverImageUrl: post.coverImageUrl, authorName: post.authorName, tags: post.tags.join(", "), seoTitleAm: post.seoTitleAm, seoTitleEn: post.seoTitleEn, seoDescriptionAm: post.seoDescriptionAm, seoDescriptionEn: post.seoDescriptionEn });
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const formatDate = (value: string) => new Intl.DateTimeFormat("en-ET", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value));

function PostEditor({ draft, context, onClose }: { draft: PostDraft; context: ManagerContext; onClose: () => void }) {
  const [form, setForm] = useState(draft); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [fields, setFields] = useState<Record<string, string>>({});
  const set = (key: keyof PostDraft, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); setFields({}); const payload = { slug: form.slug || slugify(form.titleEn) || `story-${Date.now()}`, status: form.status, titleAm: form.titleAm, titleEn: form.titleEn, excerptAm: form.excerptAm, excerptEn: form.excerptEn, contentAm: form.contentAm, contentEn: form.contentEn, coverImageUrl: form.coverImageUrl, authorName: form.authorName, tags: form.tags.split(",").map((item) => item.trim()).filter(Boolean), seoTitleAm: form.seoTitleAm, seoTitleEn: form.seoTitleEn, seoDescriptionAm: form.seoDescriptionAm, seoDescriptionEn: form.seoDescriptionEn }; try { await context.request(form.id ? `/admin/blog/posts/${form.id}` : "/admin/blog/posts", { method: form.id ? "PUT" : "POST", body: JSON.stringify(payload) }); await context.refreshAll(); context.notify(form.id ? "Story updated." : "Story created."); onClose(); } catch (saveError) { if (saveError instanceof AdminApiError) { setError(saveError.message); setFields(saveError.fields ?? {}); } else setError("Could not save this story."); } finally { setSaving(false); } }

  return <div className="et-editor-layer"><button className="et-editor-scrim" onClick={onClose} aria-label="Close editor" /><aside className="et-editor et-post-editor"><header><div><span>{form.id ? "EDIT STORY" : "NEW STORY"}</span><h2>{form.id ? form.titleEn : "Create an article"}</h2></div><button onClick={onClose}><Icon name="close" /></button></header><form onSubmit={submit}>
    <section><div className="et-form-section-title"><b>Publishing</b><span>One language is enough</span></div><div className="et-form-grid"><label><span>English title · optional</span><input value={form.titleEn} onChange={(event) => set("titleEn", event.target.value)} />{fields.titleEn && <small>{fields.titleEn}</small>}</label><label lang="am"><span>የአማርኛ ርዕስ · አማራጭ</span><input value={form.titleAm} onChange={(event) => set("titleAm", event.target.value)} />{fields.titleAm && <small>{fields.titleAm}</small>}</label><label className="wide"><span>URL slug · generated automatically if empty</span><div className="et-input-action"><input value={form.slug} onChange={(event) => set("slug", event.target.value)} /><button type="button" onClick={() => set("slug", slugify(form.titleEn))}>Generate</button></div>{fields.slug && <small>{fields.slug}</small>}</label><label><span>Status</span><select value={form.status} onChange={(event) => set("status", event.target.value as PublishStatus)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label><span>Author</span><input value={form.authorName} onChange={(event) => set("authorName", event.target.value)} /></label><label className="wide"><span>Tags, separated by commas</span><input value={form.tags} onChange={(event) => set("tags", event.target.value)} placeholder="business, booking, guides" />{fields.tags && <small>{fields.tags}</small>}</label></div></section>
    <section><div className="et-form-section-title"><b>Cover</b><span>Article imagery</span></div><div className="et-form-grid"><label className="wide"><span>Cover image URL</span><input value={form.coverImageUrl} onChange={(event) => set("coverImageUrl", event.target.value)} placeholder="https://... or /assets/..." />{fields.coverImageUrl && <small>{fields.coverImageUrl}</small>}</label>{form.coverImageUrl && <div className="et-image-preview wide post"><img src={form.coverImageUrl} alt="Article cover preview" /><span>COVER PREVIEW</span></div>}</div></section>
    <section><div className="et-form-section-title"><b>Summary</b><span>Used on blog cards and search</span></div><div className="et-form-grid"><label className="wide"><span>English excerpt</span><textarea rows={3} value={form.excerptEn} onChange={(event) => set("excerptEn", event.target.value)} /></label><label className="wide" lang="am"><span>የአማርኛ አጭር መግለጫ</span><textarea rows={3} value={form.excerptAm} onChange={(event) => set("excerptAm", event.target.value)} /></label></div></section>
    <section><div className="et-form-section-title"><b>Story</b><span>Markdown-ready bilingual content</span></div><div className="et-form-grid"><label className="wide"><span>English article</span><textarea className="article" rows={14} value={form.contentEn} onChange={(event) => set("contentEn", event.target.value)} placeholder="# Start writing…" /></label><label className="wide" lang="am"><span>የአማርኛ ጽሑፍ</span><textarea className="article" rows={14} value={form.contentAm} onChange={(event) => set("contentAm", event.target.value)} /></label>{fields.content && <p className="et-field-wide-error">{fields.content}</p>}</div></section>
    <section><div className="et-form-section-title"><b>Search preview</b><span>Optional SEO metadata</span></div><div className="et-form-grid"><label><span>English SEO title</span><input value={form.seoTitleEn} onChange={(event) => set("seoTitleEn", event.target.value)} /></label><label lang="am"><span>የአማርኛ SEO ርዕስ</span><input value={form.seoTitleAm} onChange={(event) => set("seoTitleAm", event.target.value)} /></label><label className="wide"><span>English SEO description</span><textarea rows={3} value={form.seoDescriptionEn} onChange={(event) => set("seoDescriptionEn", event.target.value)} /></label><label className="wide" lang="am"><span>የአማርኛ SEO መግለጫ</span><textarea rows={3} value={form.seoDescriptionAm} onChange={(event) => set("seoDescriptionAm", event.target.value)} /></label></div></section>
    {error && <p className="et-editor-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancel</button><button type="submit" disabled={saving}><span>{saving ? "Saving…" : form.status === "published" ? "Save and publish" : "Save draft"}</span><Icon name="arrow" /></button></footer>
  </form></aside></div>;
}

export default function BlogManager({ posts, context }: { posts: BlogPost[]; context: ManagerContext }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<"all" | PublishStatus>("all"); const [editor, setEditor] = useState<PostDraft | null>(null);
  const filtered = useMemo(() => posts.filter((post) => (status === "all" || post.status === status) && `${post.titleEn} ${post.titleAm} ${post.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [posts, query, status]);
  async function remove(post: BlogPost) { if (!window.confirm(`Remove “${post.titleEn}”? The article will disappear from the public blog.`)) return; try { await context.request(`/admin/blog/posts/${post.id}`, { method: "DELETE" }); await context.refreshAll(); context.notify("Story removed."); } catch (error) { context.notify(error instanceof Error ? error.message : "Could not remove story."); } }
  return <div className="et-admin-view"><header className="et-view-heading"><div><span className="et-eyebrow">EDITORIAL</span><h1>Ideas worth sharing.</h1><p>Write once in both languages, preview the structure, then publish when it is ready.</p></div><button className="et-primary-button" onClick={() => setEditor({ ...emptyPost })}><Icon name="plus" /> New story</button></header>
    <section className="et-list-toolbar"><label><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles or tags" /></label><div>{(["all", "published", "draft", "archived"] as const).map((item) => <button key={item} className={status === item ? "active" : ""} onClick={() => setStatus(item)}>{item}<span>{item === "all" ? posts.length : posts.filter((post) => post.status === item).length}</span></button>)}</div></section>
    <section className="et-post-grid">{filtered.length ? filtered.map((post) => <article key={post.id}><button className="et-post-card-main" onClick={() => setEditor(toDraft(post))}>{post.coverImageUrl ? <img src={post.coverImageUrl} alt="" /> : <div className="et-post-placeholder"><Icon name="posts" size={30} /></div>}<div><span className={`et-status-pill ${post.status}`}><i />{post.status}</span><h2>{post.titleEn}</h2><p lang="am">{post.titleAm}</p><small>{post.excerptEn || "No excerpt yet."}</small><footer><span>{post.authorName}</span><time>{formatDate(post.updatedAt)}</time></footer></div></button><div className="et-post-actions"><button onClick={() => setEditor(toDraft(post))}><Icon name="edit" /> Edit</button><button className="danger" onClick={() => void remove(post)}><Icon name="trash" /></button></div></article>) : <div className="et-empty-state et-empty-grid"><i><Icon name="posts" size={27} /></i><h3>No matching stories</h3><p>Create the first article or adjust the filter.</p><button onClick={() => setEditor({ ...emptyPost })}>Create story</button></div>}</section>
    {editor && <PostEditor key={editor.id ?? "new"} draft={editor} context={context} onClose={() => setEditor(null)} />}
  </div>;
}
