"use client";

import { useMemo, useState } from "react";
import type { Lead, LeadStatus } from "../types";
import type { ManagerContext } from "./AdminApp";
import Icon from "./Icon";

const statuses: LeadStatus[] = ["new", "contacted", "qualified", "converted", "closed", "spam"];
const formatDate = (value: string, full = false) => new Intl.DateTimeFormat("en-ET", full ? { dateStyle: "medium", timeStyle: "short" } : { month: "short", day: "numeric", year: "numeric" }).format(new Date(value));

export default function LeadManager({ leads, context }: { leads: Lead[]; context: ManagerContext }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<"all" | LeadStatus>("all"); const [selected, setSelected] = useState<Lead | null>(null); const [updating, setUpdating] = useState("");
  const filtered = useMemo(() => leads.filter((lead) => (status === "all" || lead.status === status) && `${lead.name} ${lead.email} ${lead.phone} ${lead.businessName ?? ""}`.toLowerCase().includes(query.toLowerCase())), [leads, query, status]);
  async function changeStatus(lead: Lead, next: LeadStatus) { setUpdating(lead.id); try { await context.request(`/admin/leads/${lead.id}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }); await context.refreshAll(); setSelected((current) => current?.id === lead.id ? { ...current, status: next } : current); context.notify("Lead status updated."); } catch (error) { context.notify(error instanceof Error ? error.message : "Could not update the lead."); } finally { setUpdating(""); } }

  return <div className="et-admin-view"><header className="et-view-heading"><div><span className="et-eyebrow">RELATIONSHIPS</span><h1>Every enquiry, remembered.</h1><p>Follow registrations from first contact through onboarding without losing the original details.</p></div><div className="et-lead-summary"><i /><span><b>{leads.filter((lead) => lead.status === "new").length}</b> need attention</span></div></header>
    <section className="et-list-toolbar et-lead-toolbar"><label><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, phone or business" /></label><select value={status} onChange={(event) => setStatus(event.target.value as "all" | LeadStatus)}><option value="all">All lead stages</option>{statuses.map((item) => <option key={item} value={item}>{item}</option>)}</select></section>
    <section className="et-data-panel"><header className="et-lead-table-head"><span>Person</span><span>Request</span><span>Delivery</span><span>Stage</span><span>Received</span></header>{filtered.length ? filtered.map((lead) => <button className="et-lead-row" key={lead.id} onClick={() => setSelected(lead)}><div className="et-person"><i>{lead.name.slice(0, 1).toUpperCase()}</i><span><b>{lead.name}</b><small>{lead.email}</small></span></div><div><b>{lead.businessName || (lead.kind === "demo" ? "Demo registration" : "Contact message")}</b><small>{lead.phone}</small></div><span className={`et-delivery ${lead.emailStatus}`}><i />{lead.emailStatus}</span><span className={`et-lead-stage ${lead.status}`}>{lead.status}</span><time>{formatDate(lead.createdAt)}</time></button>) : <div className="et-empty-state"><i><Icon name="leads" size={27} /></i><h3>No matching leads</h3><p>New registrations and contact requests will appear here.</p></div>}</section>
    {selected && <div className="et-lead-detail-layer"><button className="et-editor-scrim" onClick={() => setSelected(null)} aria-label="Close lead"/><aside className="et-lead-detail"><header><div><span>LEAD PROFILE</span><h2>{selected.name}</h2></div><button onClick={() => setSelected(null)}><Icon name="close" /></button></header><div className="et-lead-identity"><i>{selected.name.slice(0, 1).toUpperCase()}</i><div><h3>{selected.businessName || "Individual enquiry"}</h3><p>{selected.kind === "demo" ? "Demo registration" : "Contact request"} · {selected.locale}</p></div></div><section><span>CONTACT</span><a href={`mailto:${selected.email}`}>{selected.email}</a><a href={`tel:${selected.phone}`}>{selected.phone}</a></section>{selected.message && <section><span>MESSAGE</span><p>{selected.message}</p></section>}<section><span>SUBMISSION</span><dl><div><dt>Source</dt><dd>{selected.source}</dd></div><div><dt>Received</dt><dd>{formatDate(selected.createdAt, true)}</dd></div><div><dt>Email delivery</dt><dd className={selected.emailStatus}>{selected.emailStatus}</dd></div></dl></section><section><span>SALES STAGE</span><div className="et-stage-options">{statuses.filter((item) => item !== "spam").map((item) => <button key={item} className={selected.status === item ? "active" : ""} disabled={updating === selected.id} onClick={() => void changeStatus(selected, item)}>{selected.status === item && <Icon name="check" size={13} />}{item}</button>)}</div><button className="et-mark-spam" disabled={updating === selected.id} onClick={() => void changeStatus(selected, "spam")}>Mark as spam</button></section></aside></div>}
  </div>;
}
